Repository ASFHyP3/hyp3-metadata-templates, pull requests merged in 2021-06, with the labels that each got.

#79 add stub insar data for testing
  hyp3_metadata/data/insar/insar_amp.tif
  hyp3_metadata/data/insar/insar_color_phase.png
  hyp3_metadata/data/insar/insar_color_phase.png.aux.xml
  hyp3_metadata/data/insar/insar_corr.tif
  hyp3_metadata/data/insar/insar_dem.tif
  hyp3_metadata/data/insar/insar_inc_map.tif
  hyp3_metadata/data/insar/insar_los_disp.tif
  hyp3_metadata/data/insar/insar_lv_phi.tif
  hyp3_metadata/data/insar/insar_lv_theta.tif
  hyp3_metadata/data/insar/insar_unw_phase.png
  hyp3_metadata/data/insar/insar_unw_phase.png.aux.xml
  hyp3_metadata/data/insar/insar_unw_phase.tif
  hyp3_metadata/data/insar/insar_vert_disp.tif
  hyp3_metadata/data/insar/insar_wrapped_phase.tif
Labels: bumpless

#80 add reference_file to rtc/insar template payloads
  hyp3_metadata/insar.py
  hyp3_metadata/rtc.py
Labels: bumpless

#72 Insar templates
  CHANGELOG.md
  hyp3_metadata/__main__.py
  hyp3_metadata/create.py
  hyp3_metadata/data/insar/insar_amp.tif
  hyp3_metadata/data/insar/insar_color_phase.png
  hyp3_metadata/data/insar/insar_color_phase.png.aux.xml
  hyp3_metadata/data/insar/insar_corr.tif
  hyp3_metadata/data/insar/insar_dem.tif
  hyp3_metadata/data/insar/insar_inc_map.tif
  hyp3_metadata/data/insar/insar_los_disp.tif
  hyp3_metadata/data/insar/insar_lv_phi.tif
  hyp3_metadata/data/insar/insar_lv_theta.tif
  hyp3_metadata/data/insar/insar_unw_phase.png
  hyp3_metadata/data/insar/insar_unw_phase.png.aux.xml
  hyp3_metadata/data/insar/insar_unw_phase.tif
  hyp3_metadata/data/insar/insar_vert_disp.tif
  hyp3_metadata/data/insar/insar_wrapped_phase.tif
  hyp3_metadata/data/rtc/rtc.png
  hyp3_metadata/data/rtc/rtc.png.aux.xml
  hyp3_metadata/data/rtc/rtc_VH.tif
  hyp3_metadata/data/rtc/rtc_VV.tif
  hyp3_metadata/data/rtc/rtc_area.tif
  hyp3_metadata/data/rtc/rtc_dem.png
  hyp3_metadata/data/rtc/rtc_dem.tif
  hyp3_metadata/data/rtc/rtc_inc_map.tif
  hyp3_metadata/data/rtc/rtc_ls_map.tif
  hyp3_metadata/data/rtc/rtc_rgb.png
  hyp3_metadata/data/rtc/rtc_rgb.png.aux.xml
  hyp3_metadata/data/rtc/rtc_rgb.tif
  hyp3_metadata/insar.py
  hyp3_metadata/rtc.py
  hyp3_metadata/templates/arc.xml.j2
  hyp3_metadata/templates/insar/amp_tif.xml.j2
  hyp3_metadata/templates/insar/color_phase_png.xml.j2
  hyp3_metadata/templates/insar/corr_tif.xml.j2
  hyp3_metadata/templates/insar/dem.xml.j2
  hyp3_metadata/templates/insar/inc_map_tif.xml.j2
  hyp3_metadata/templates/insar/insar.xml.j2
  hyp3_metadata/templates/insar/insar_dem.xml.j2
  hyp3_metadata/templates/insar/los_disp_tif.xml.j2
  hyp3_metadata/templates/insar/lv_phi_tif.xml.j2
  hyp3_metadata/templates/insar/lv_theta_tif.xml.j2
  hyp3_metadata/templates/insar/readme.md.txt.j2
  hyp3_metadata/templates/insar/unw_phase_png.xml.j2
  hyp3_metadata/templates/insar/unw_phase_tif.xml.j2
  hyp3_metadata/templates/insar/vert_disp_tif.xml.j2
  hyp3_metadata/templates/insar/wrapped_phase_tif.xml.j2
  hyp3_metadata/templates/rtc/readme.md.txt.j2
  hyp3_metadata/util.py
  tests/conftest.py
  tests/test_insar_gamma.py
  tests/test_rtc_gamma.py
Labels: documentation, minor

#82 updates to InSAR template content
  hyp3_metadata/templates/insar/amp_tif.xml.j2
  hyp3_metadata/templates/insar/corr_tif.xml.j2
  hyp3_metadata/templates/insar/dem.xml.j2
  hyp3_metadata/templates/insar/inc_map_tif.xml.j2
  hyp3_metadata/templates/insar/los_disp_tif.xml.j2
  hyp3_metadata/templates/insar/lv_phi_tif.xml.j2
  hyp3_metadata/templates/insar/lv_theta_tif.xml.j2
  hyp3_metadata/templates/insar/unw_phase_png.xml.j2
  hyp3_metadata/templates/insar/unw_phase_tif.xml.j2
  hyp3_metadata/templates/insar/vert_disp_tif.xml.j2
  hyp3_metadata/templates/insar/wrapped_phase_tif.xml.j2
Labels: bumpless, documentation

#83 Insar fixes
  hyp3_metadata/__main__.py
  hyp3_metadata/insar.py
  hyp3_metadata/rtc.py
Labels: bumpless

#84 create insar inc_map xml
  hyp3_metadata/insar.py
  hyp3_metadata/templates/insar/inc_map_tif.xml.j2
  tests/test_insar_gamma.py
Labels: bumpless

#85 minor fixes
  hyp3_metadata/insar.py
  tests/test_insar_gamma.py
Labels: bumpless

#81 RELEASE: 1.2.0
  CHANGELOG.md
  hyp3_metadata/__main__.py
  hyp3_metadata/create.py
  hyp3_metadata/data/insar/insar_amp.tif
  hyp3_metadata/data/insar/insar_color_phase.png
  hyp3_metadata/data/insar/insar_color_phase.png.aux.xml
  hyp3_metadata/data/insar/insar_corr.tif
  hyp3_metadata/data/insar/insar_dem.tif
  hyp3_metadata/data/insar/insar_inc_map.tif
  hyp3_metadata/data/insar/insar_los_disp.tif
  hyp3_metadata/data/insar/insar_lv_phi.tif
  hyp3_metadata/data/insar/insar_lv_theta.tif
  hyp3_metadata/data/insar/insar_unw_phase.png
  hyp3_metadata/data/insar/insar_unw_phase.png.aux.xml
  hyp3_metadata/data/insar/insar_unw_phase.tif
  hyp3_metadata/data/insar/insar_vert_disp.tif
  hyp3_metadata/data/insar/insar_wrapped_phase.tif
  hyp3_metadata/data/rtc/rtc.png
  hyp3_metadata/data/rtc/rtc.png.aux.xml
  hyp3_metadata/data/rtc/rtc_VH.tif
  hyp3_metadata/data/rtc/rtc_VV.tif
  hyp3_metadata/data/rtc/rtc_area.tif
  hyp3_metadata/data/rtc/rtc_dem.png
  hyp3_metadata/data/rtc/rtc_dem.tif
  hyp3_metadata/data/rtc/rtc_inc_map.tif
  hyp3_metadata/data/rtc/rtc_ls_map.tif
  hyp3_metadata/data/rtc/rtc_rgb.png
  hyp3_metadata/data/rtc/rtc_rgb.png.aux.xml
  hyp3_metadata/data/rtc/rtc_rgb.tif
  hyp3_metadata/insar.py
  hyp3_metadata/rtc.py
  hyp3_metadata/templates/arc.xml.j2
  hyp3_metadata/templates/insar/amp_tif.xml.j2
  hyp3_metadata/templates/insar/color_phase_png.xml.j2
  hyp3_metadata/templates/insar/corr_tif.xml.j2
  hyp3_metadata/templates/insar/dem.xml.j2
  hyp3_metadata/templates/insar/inc_map_tif.xml.j2
  hyp3_metadata/templates/insar/insar.xml.j2
  hyp3_metadata/templates/insar/insar_dem.xml.j2
  hyp3_metadata/templates/insar/los_disp_tif.xml.j2
  hyp3_metadata/templates/insar/lv_phi_tif.xml.j2
  hyp3_metadata/templates/insar/lv_theta_tif.xml.j2
  hyp3_metadata/templates/insar/readme.md.txt.j2
  hyp3_metadata/templates/insar/unw_phase_png.xml.j2
  hyp3_metadata/templates/insar/unw_phase_tif.xml.j2
  hyp3_metadata/templates/insar/vert_disp_tif.xml.j2
  hyp3_metadata/templates/insar/wrapped_phase_tif.xml.j2
  hyp3_metadata/templates/rtc/readme.md.txt.j2
  hyp3_metadata/util.py
  tests/conftest.py
  tests/test_insar_gamma.py
  tests/test_rtc_gamma.py
Labels: documentation, minor

#87 RELEASE 1.2.1
  CHANGELOG.md
  hyp3_metadata/__init__.py
  tests/test_insar_gamma.py
  tests/test_rtc_gamma.py
Labels: patch

#88 Small fixes for InSAR templates
  CHANGELOG.md
  hyp3_metadata/templates/insar/color_phase_png.xml.j2
  hyp3_metadata/templates/insar/lv_phi_tif.xml.j2
  hyp3_metadata/templates/insar/readme.md.txt.j2
  hyp3_metadata/templates/insar/unw_phase_tif.xml.j2
  hyp3_metadata/templates/insar/wrapped_phase_tif.xml.j2
Labels: patch

#89 Release 1.2.2
  CHANGELOG.md
  hyp3_metadata/templates/insar/color_phase_png.xml.j2
  hyp3_metadata/templates/insar/lv_phi_tif.xml.j2
  hyp3_metadata/templates/insar/readme.md.txt.j2
  hyp3_metadata/templates/insar/unw_phase_tif.xml.j2
  hyp3_metadata/templates/insar/wrapped_phase_tif.xml.j2
Labels: patch

#91 drop ALLOW_TAG_PREFIX option deprecated in git-release v4.0.0
  .github/workflows/release.yml
Labels: bumpless

#92 Additional edits to InSAR metadata templates
  CHANGELOG.md
  hyp3_metadata/templates/browse/browse-color.xml.j2
  hyp3_metadata/templates/browse/browse-greyscale.xml.j2
  hyp3_metadata/templates/dem/dem-cop.xml.j2
  hyp3_metadata/templates/dem/dem-eu.xml.j2
  hyp3_metadata/templates/dem/dem-gimp.xml.j2
  hyp3_metadata/templates/dem/dem-ifsar.xml.j2
  hyp3_metadata/templates/dem/dem-ned.xml.j2
  hyp3_metadata/templates/dem/dem-rema.xml.j2
  hyp3_metadata/templates/dem/dem-srtm.xml.j2
  hyp3_metadata/templates/insar/inc_map_tif.xml.j2
  hyp3_metadata/templates/insar/lv_theta_tif.xml.j2
  hyp3_metadata/templates/insar/readme.md.txt.j2
  hyp3_metadata/templates/insar/unw_phase_png.xml.j2
  hyp3_metadata/templates/insar/unw_phase_tif.xml.j2
  hyp3_metadata/templates/rtc/area.xml.j2
  hyp3_metadata/templates/rtc/inc_map.xml.j2
  hyp3_metadata/templates/rtc/ls_map.xml.j2
  hyp3_metadata/templates/rtc/product.xml.j2
  hyp3_metadata/templates/rtc/readme.md.txt.j2
  hyp3_metadata/templates/rtc/rgb.xml.j2
Labels: patch

#93 RELEASE: 1.2.3
  .github/workflows/release.yml
  CHANGELOG.md
  hyp3_metadata/templates/browse/browse-color.xml.j2
  hyp3_metadata/templates/browse/browse-greyscale.xml.j2
  hyp3_metadata/templates/dem/dem-cop.xml.j2
  hyp3_metadata/templates/dem/dem-eu.xml.j2
  hyp3_metadata/templates/dem/dem-gimp.xml.j2
  hyp3_metadata/templates/dem/dem-ifsar.xml.j2
  hyp3_metadata/templates/dem/dem-ned.xml.j2
  hyp3_metadata/templates/dem/dem-rema.xml.j2
  hyp3_metadata/templates/dem/dem-srtm.xml.j2
  hyp3_metadata/templates/insar/inc_map_tif.xml.j2
  hyp3_metadata/templates/insar/lv_theta_tif.xml.j2
  hyp3_metadata/templates/insar/readme.md.txt.j2
  hyp3_metadata/templates/insar/unw_phase_png.xml.j2
  hyp3_metadata/templates/insar/unw_phase_tif.xml.j2
  hyp3_metadata/templates/rtc/area.xml.j2
  hyp3_metadata/templates/rtc/inc_map.xml.j2
  hyp3_metadata/templates/rtc/ls_map.xml.j2
  hyp3_metadata/templates/rtc/product.xml.j2
  hyp3_metadata/templates/rtc/readme.md.txt.j2
  hyp3_metadata/templates/rtc/rgb.xml.j2
Labels: patch

#96 Update release.yml
  .github/workflows/release.yml
Labels: CI/CD, bumpless
