Repository ASFHyP3/hyp3-metadata-templates, pull requests merged in 2021-04, with the labels that each got.

#66 Correction to area map xml
  CHANGELOG.md
  hyp3_metadata/create.py
  hyp3_metadata/templates/area.xml.j2
  hyp3_metadata/templates/browse/browse-color.xml.j2
  hyp3_metadata/templates/browse/browse-greyscale.xml.j2
  hyp3_metadata/templates/dem/dem-cop.xml.j2
  hyp3_metadata/templates/dem/dem-eu.xml.j2
  hyp3_metadata/templates/dem/dem-gimp.xml.j2
  hyp3_metadata/templates/dem/dem-ifsar.xml.j2
  hyp3_metadata/templates/dem/dem-ned.xml.j2
  hyp3_metadata/templates/dem/dem-rema.xml.j2
  hyp3_metadata/templates/dem/dem-srtm.xml.j2
  hyp3_metadata/templates/inc_map.xml.j2
  hyp3_metadata/templates/ls_map.xml.j2
  hyp3_metadata/templates/product.xml.j2
  hyp3_metadata/templates/readme.md.txt.j2
  hyp3_metadata/templates/rgb.xml.j2
Labels: documentation

#69 Add visualization guidance for RGB Decomp in ArcGIS
  hyp3_metadata/templates/rgb.xml.j2
Labels: bumpless, documentation

#68 Release v0.4.2
  CHANGELOG.md
  hyp3_metadata/create.py
  hyp3_metadata/templates/area.xml.j2
  hyp3_metadata/templates/browse/browse-color.xml.j2
  hyp3_metadata/templates/browse/browse-greyscale.xml.j2
  hyp3_metadata/templates/dem/dem-cop.xml.j2
  hyp3_metadata/templates/dem/dem-eu.xml.j2
  hyp3_metadata/templates/dem/dem-gimp.xml.j2
  hyp3_metadata/templates/dem/dem-ifsar.xml.j2
  hyp3_metadata/templates/dem/dem-ned.xml.j2
  hyp3_metadata/templates/dem/dem-rema.xml.j2
  hyp3_metadata/templates/dem/dem-srtm.xml.j2
  hyp3_metadata/templates/inc_map.xml.j2
  hyp3_metadata/templates/ls_map.xml.j2
  hyp3_metadata/templates/product.xml.j2
  hyp3_metadata/templates/readme.md.txt.j2
  hyp3_metadata/templates/rgb.xml.j2
Labels: patch

#70 Simplified credit statement for imagery
  hyp3_metadata/templates/rtc/product.xml.j2
  hyp3_metadata/templates/rtc/readme.md.txt.j2
Labels: bumpless, documentation
