Repository ASFHyP3/hyp3-metadata-templates, pull requests merged in 2021-03, with the labels that each got.

#50 Updating documentation to include Copernicus DEM
  .github/workflows/test-and-build.yml
  CHANGELOG.md
  conda-env.yml
  hyp3_metadata/dem/dem-cop30.xml.j2
  hyp3_metadata/macros.j2
  hyp3_metadata/readme.md.txt.j2
Labels: documentation, minor

#52 actually generate cop dem xml, separate cop dem description from spec…
  hyp3_metadata/create.py
  hyp3_metadata/dem/dem-cop.xml.j2
  hyp3_metadata/macros.j2
Labels: bumpless

#55 remove 'scattering area' from list of rgb xml search terms
  hyp3_metadata/templates/rgb.xml.j2
Labels: bumpless

#57 Release RGB xml, code to generate Copernicus xml
  .github/workflows/test-and-build.yml
  CHANGELOG.md
  README.md
  conda-env.yml
  hyp3_metadata/__main__.py
  hyp3_metadata/create.py
  hyp3_metadata/data/__init__.py
  hyp3_metadata/data/rtc.png
  hyp3_metadata/data/rtc.png.aux.xml
  hyp3_metadata/data/rtc_VH.tif
  hyp3_metadata/data/rtc_VV.tif
  hyp3_metadata/data/rtc_area.tif
  hyp3_metadata/data/rtc_dem.png
  hyp3_metadata/data/rtc_dem.tif
  hyp3_metadata/data/rtc_inc_map.tif
  hyp3_metadata/data/rtc_ls_map.tif
  hyp3_metadata/data/rtc_rgb.png
  hyp3_metadata/data/rtc_rgb.png.aux.xml
  hyp3_metadata/data/rtc_rgb.tif
  hyp3_metadata/templates/arc.xml.j2
  hyp3_metadata/templates/area.xml.j2
  hyp3_metadata/templates/browse/browse-color.xml.j2
  hyp3_metadata/templates/browse/browse-greyscale.xml.j2
  hyp3_metadata/templates/browse/browse.xml.j2
  hyp3_metadata/templates/contact-asf.xml.j2
  hyp3_metadata/templates/dem/dem-cop.xml.j2
  hyp3_metadata/templates/dem/dem-eu.xml.j2
  hyp3_metadata/templates/dem/dem-gimp.xml.j2
  hyp3_metadata/templates/dem/dem-ifsar.xml.j2
  hyp3_metadata/templates/dem/dem-ned.xml.j2
  hyp3_metadata/templates/dem/dem-rema.xml.j2
  hyp3_metadata/templates/dem/dem-srtm.xml.j2
  hyp3_metadata/templates/dem/dem.xml.j2
  hyp3_metadata/templates/inc_map.xml.j2
  hyp3_metadata/templates/ls_map.xml.j2
  hyp3_metadata/templates/macros.j2
  hyp3_metadata/templates/product.xml.j2
  hyp3_metadata/templates/readme.md.txt.j2
  hyp3_metadata/templates/rgb.xml.j2
  hyp3_metadata/util.py
  setup.py
  tests/conftest.py
  tests/test_rtc_gamma.py
Labels: minor

#61 update copernicus name to GLO-30
  hyp3_metadata/__main__.py
  hyp3_metadata/templates/macros.j2
Labels: bumpless

#59 Add missing information in Copernicus DEM xml
  hyp3_metadata/templates/area.xml.j2
  hyp3_metadata/templates/browse/browse-color.xml.j2
  hyp3_metadata/templates/browse/browse-greyscale.xml.j2
  hyp3_metadata/templates/dem/dem-cop.xml.j2
  hyp3_metadata/templates/dem/dem-eu.xml.j2
  hyp3_metadata/templates/dem/dem-gimp.xml.j2
  hyp3_metadata/templates/dem/dem-ifsar.xml.j2
  hyp3_metadata/templates/dem/dem-ned.xml.j2
  hyp3_metadata/templates/dem/dem-rema.xml.j2
  hyp3_metadata/templates/dem/dem-srtm.xml.j2
  hyp3_metadata/templates/inc_map.xml.j2
  hyp3_metadata/templates/ls_map.xml.j2
  hyp3_metadata/templates/macros.j2
  hyp3_metadata/templates/product.xml.j2
  hyp3_metadata/templates/readme.md.txt.j2
  hyp3_metadata/templates/rgb.xml.j2
Labels: bumpless

#64 fix dem template lookup for GLO-30
  hyp3_metadata/__main__.py
  hyp3_metadata/create.py
  hyp3_metadata/util.py
  tests/test_rtc_gamma.py
Labels: bumpless

#63 Release Copernicus DEM xml updates, other content tweaks
  CHANGELOG.md
  README.md
  hyp3_metadata/__main__.py
  hyp3_metadata/create.py
  hyp3_metadata/templates/area.xml.j2
  hyp3_metadata/templates/browse/browse-color.xml.j2
  hyp3_metadata/templates/browse/browse-greyscale.xml.j2
  hyp3_metadata/templates/dem/dem-cop.xml.j2
  hyp3_metadata/templates/dem/dem-eu.xml.j2
  hyp3_metadata/templates/dem/dem-gimp.xml.j2
  hyp3_metadata/templates/dem/dem-ifsar.xml.j2
  hyp3_metadata/templates/dem/dem-ned.xml.j2
  hyp3_metadata/templates/dem/dem-rema.xml.j2
  hyp3_metadata/templates/dem/dem-srtm.xml.j2
  hyp3_metadata/templates/inc_map.xml.j2
  hyp3_metadata/templates/ls_map.xml.j2
  hyp3_metadata/templates/macros.j2
  hyp3_metadata/templates/product.xml.j2
  hyp3_metadata/templates/readme.md.txt.j2
  hyp3_metadata/templates/rgb.xml.j2
  hyp3_metadata/util.py
  setup.py
  tests/test_rtc_gamma.py
Labels: patch
