Repository ASFHyP3/hyp3-metadata-templates, pull requests merged in 2021-07, with the labels that each got.

#99 update readme instructions for creating sample metadata set
  README.md
Labels: bumpless

#97 InSAR Water Mask descriptions
  CHANGELOG.md
  hyp3_metadata/data/insar/insar_water_mask.tif
  hyp3_metadata/insar.py
  hyp3_metadata/templates/insar/readme.md.txt.j2
  hyp3_metadata/templates/insar/water_mask_tif.xml.j2
  tests/test_insar_gamma.py
Labels: documentation, patch

#102 Release water mask metadata
  .github/workflows/release.yml
  CHANGELOG.md
  README.md
  hyp3_metadata/data/insar/insar_water_mask.tif
  hyp3_metadata/insar.py
  hyp3_metadata/templates/insar/readme.md.txt.j2
  hyp3_metadata/templates/insar/water_mask_tif.xml.j2
  tests/test_insar_gamma.py
Labels: patch

#103 Add metadata for ellipsoid incidence angle file in InSAR package
  .github/workflows/test-and-build.yml
  CHANGELOG.md
  environment.yml
  hyp3_metadata/data/insar/insar_inc_map_ell.tif
  hyp3_metadata/insar.py
  hyp3_metadata/templates/insar/inc_map_ell_tif.xml.j2
  hyp3_metadata/templates/insar/readme.md.txt.j2
  tests/test_insar_gamma.py
Labels: documentation, patch

#105 indicate GSHHG L2 used in water masks in addition to L1 and L5
  hyp3_metadata/templates/insar/water_mask_tif.xml.j2
Labels: bumpless

#106 add .github/CODEOWNERS
  .github/CODEOWNERS
Labels: bumpless

#107 Release 1.2.5
  .github/CODEOWNERS
  .github/workflows/test-and-build.yml
  CHANGELOG.md
  environment.yml
  hyp3_metadata/data/insar/insar_inc_map_ell.tif
  hyp3_metadata/insar.py
  hyp3_metadata/templates/insar/inc_map_ell_tif.xml.j2
  hyp3_metadata/templates/insar/readme.md.txt.j2
  hyp3_metadata/templates/insar/water_mask_tif.xml.j2
  tests/test_insar_gamma.py
Labels: patch

#109 Add back language including large inland waterbodies in water mask description
  CHANGELOG.md
  hyp3_metadata/templates/insar/readme.md.txt.j2
  hyp3_metadata/templates/insar/water_mask_tif.xml.j2
Labels: documentation, patch
